STATE_QUERIES = {
    "Andhra Pradesh": '"Andhra Pradesh" OR Amaravati OR Visakhapatnam',
    "Telangana": "Telangana OR Hyderabad",
    "Tamil Nadu": '"Tamil Nadu" OR Chennai OR Coimbatore',
    "Karnataka": "Karnataka OR Bengaluru",
    "Maharashtra": "Maharashtra OR Mumbai OR Pune",
    "Kerala": "Kerala OR Thiruvananthapuram",
    "Madhya Pradesh": '"Madhya Pradesh" OR Bhopal',
    "West Bengal": '"West Bengal" OR Kolkata',      # ← key fix
    "Uttar Pradesh": '"Uttar Pradesh" OR Lucknow OR Kanpur OR Varanasi',
    "Himachal Pradesh": '"Himachal Pradesh" OR Shimla',
    "Arunachal Pradesh": '"Arunachal Pradesh" OR Itanagar',
    "Jammu and Kashmir": '"Jammu and Kashmir" OR Srinagar OR Jammu',
    "Andaman and Nicobar Islands": '"Andaman and Nicobar Islands" OR "Port Blair"',
    # single word states don't need quotes
    "Bihar": "Bihar OR Patna",
    "Assam": "Assam OR Guwahati",
    "Odisha": "Odisha OR Bhubaneswar",
    "Punjab": "Punjab OR Chandigarh",
    "Haryana": "Haryana OR Chandigarh",
    "Goa": "Goa OR Panaji",
    "Delhi": "Delhi OR New Delhi",
    "Gujarat": "Gujarat OR Gandhinagar",
    "Rajasthan": "Rajasthan OR Jaipur",
    "Chhattisgarh": "Chhattisgarh OR Raipur",
    "Jharkhand": "Jharkhand OR Ranchi",
    "Uttarakhand": "Uttarakhand OR Dehradun",
    "Manipur": "Manipur OR Imphal",
    "Meghalaya": "Meghalaya OR Shillong",
    "Mizoram": "Mizoram OR Aizawl",
    "Nagaland": "Nagaland OR Kohima",
    "Sikkim": "Sikkim OR Gangtok",
    "Tripura": "Tripura OR Agartala",
    "Chandigarh": "Chandigarh",
    "Puducherry": "Puducherry OR Pondicherry",
    "Ladakh": "Ladakh OR Leh OR Kargil",
    "Dadra and Nagar Haveli and Daman and Diu": '"Daman and Diu" OR Silvassa',
}